name: Proposer une fonctionnalité
description: Une idée pour améliorer Team Tasks
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: need
    attributes:
      label: Besoin
      description: En tant que..., je veux..., afin de...
    validations:
      required: true

  - type: textarea
    id: criteria
    attributes:
      label: Critères d'acceptation
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
